name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        cd tests
        pytest
    

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/

    - name: Package Lambda function
      run: |
        cd app
        # zip -r ../lambda_function_payload.zip .
        zip -qq -r lambda_function_payload.zip "app.py"

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform/

    - name: Upload Lambda package to S3
      run: |
        aws s3 cp lambda_function_payload.zip s3://bbog-my-lambda-functions-bucket-jdhg/

    - name: Update Lambda function code
      run: |
        aws lambda update-function-code --function-name votingFunction --s3-bucket bbog-my-lambda-functions-bucket-jdhg --s3-key lambda_function_payload.zip
